# --- !Ups

CREATE TABLE SIGNALEMENT
(
    ID UUID PRIMARY KEY,
    TYPE_ETABLISSEMENT VARCHAR NOT NULL,
    CATEGORIE_ETABLISSEMENT VARCHAR NOT NULL,
    PRECISION_ANOMALIE VARCHAR NOT NULL,
    NOM_ETABLISSEMENT VARCHAR NOT NULL,
    ADRESSE_ETABLISSEMENT VARCHAR NOT NULL,
    DESCRIPTION VARCHAR NOT NULL,
    PRENOM VARCHAR,
    NOM VARCHAR NOT NULL,
    EMAIL VARCHAR NOT NULL,
    PHOTO VARCHAR
);

# --- !Downs

DROP TABLE SIGNALEMENT;