# --- !Ups

ALTER TABLE USERS RENAME COLUMN EMAIL TO LOGIN;
ALTER TABLE USERS ADD OR REPLACE CONSTRAINT LOGIN_UNIQUE UNIQUE(LOGIN);

ALTER TABLE USERS ADD COLUMN EMAIL VARCHAR;
UPDATE USERS SET EMAIL = LOGIN;


ALTER TABLE USERS ADD COLUMN ACTIVATION_KEY VARCHAR;

ALTER TABLE USERS ALTER COLUMN FIRSTNAME DROP NOT NULL;
ALTER TABLE USERS ALTER COLUMN LASTNAME DROP NOT NULL;

# --- !Downs

ALTER TABLE USERS DROP COLUMN EMAIL;
ALTER TABLE USERS RENAME COLUMN LOGIN TO EMAIL;

ALTER TABLE USERS DROP COLUMN ACTIVATION_KEY;
