# --- !Ups

ALTER TABLE SIGNALEMENT ADD COLUMN date_creation TIMESTAMP;
UPDATE SIGNALEMENT SET date_creation = now() WHERE date_creation IS NULL;
ALTER TABLE SIGNALEMENT ALTER COLUMN date_creation SET DEFAULT now();
ALTER TABLE SIGNALEMENT ALTER COLUMN date_creation SET NOT NULL;

ALTER TABLE SIGNALEMENT ADD COLUMN date_constat DATE;
UPDATE SIGNALEMENT SET date_constat = now() WHERE date_constat IS NULL;
ALTER TABLE SIGNALEMENT ALTER COLUMN date_constat SET NOT NULL;

ALTER TABLE SIGNALEMENT ADD COLUMN heure_constat NUMERIC;

# --- !Downs

ALTER TABLE SIGNALEMENT DROP date_creation;
ALTER TABLE SIGNALEMENT DROP date_constat;
ALTER TABLE SIGNALEMENT DROP heure_constat;