# --- !Ups

CREATE TABLE USERS
(
    ID UUID PRIMARY KEY,
    EMAIL VARCHAR NOT NULL,
    PASSWORD VARCHAR NOT NULL,
    FIRSTNAME VARCHAR NOT NULL,
    LASTNAME VARCHAR NOT NULL,
    ROLE VARCHAR NOT NULL
);

# --- !Downs

DROP TABLE USERS;