# --- !Ups

ALTER TABLE SIGNALEMENT ALTER COLUMN date_constat DROP NOT NULL;

ALTER TABLE SIGNALEMENT ALTER COLUMN precision TYPE VARCHAR[] USING array[precision];
ALTER TABLE SIGNALEMENT RENAME COLUMN precision TO details;

ALTER TABLE SIGNALEMENT ALTER COLUMN sous_categorie TYPE VARCHAR[] USING array[sous_categorie];
ALTER TABLE SIGNALEMENT RENAME COLUMN sous_categorie TO sous_categories;

CREATE TABLE USERS
(
    ID UUID PRIMARY KEY,
    EMAIL VARCHAR NOT NULL,
    PASSWORD VARCHAR NOT NULL,
    FIRSTNAME VARCHAR NOT NULL,
    LASTNAME VARCHAR NOT NULL,
    ROLE VARCHAR NOT NULL
);

INSERT INTO USERS VALUES ('e6de6b48-1c53-4d3e-a7ff-dd9b643073cf', 'jerome.rivals@gmail.com', '$2a$10$z5OdWpY05I9tvCJt0EplWOqLWLi6TFCyzZA4DoVlvCWbjmgCsQzwC', 'Jérôme', 'RIVALS', 'Admin')

# --- !Downs

ALTER TABLE SIGNALEMENT RENAME COLUMN details TO precision;
ALTER TABLE SIGNALEMENT ALTER COLUMN precision TYPE VARCHAR USING precision[1];

ALTER TABLE SIGNALEMENT RENAME COLUMN sous_categories TO sous_categorie;
ALTER TABLE SIGNALEMENT ALTER COLUMN sous_categorie TYPE VARCHAR USING sous_categorie[1];

DROP TABLE USERS;
