# --- !Ups

CREATE TABLE EVENTS
(
    ID UUID PRIMARY KEY,
    REPORT_ID UUID NOT NULL,
    USER_ID UUID NOT NULL,
    CREATION_DATE DATE NOT NULL,
    EVENT_TYPE VARCHAR NOT NULL,
    ACTION VARCHAR NOT NULL,
    RESULT_ACTION VARCHAR NOT NULL,
    DETAIL VARCHAR NOT NULL
);

ALTER TABLE EVENTS ADD CONSTRAINT FK_EVENTS_REPORT FOREIGN KEY (REPORT_ID) REFERENCES SIGNALEMENT(ID);
ALTER TABLE EVENTS ADD CONSTRAINT FK_EVENTS_USERS FOREIGN KEY (USER_ID) REFERENCES USERS(ID);

# --- !Downs

ALTER TABLE EVENTS DROP CONSTRAINT FK_EVENTS_REPORT;
ALTER TABLE EVENTS DROP CONSTRAINT FK_EVENTS_USERS;

DROP TABLE EVENTS;
