package repositories.company.accessinheritancemigration

import repositories.CRUDRepositoryInterface

trait CompanyAccessInheritanceMigrationRepositoryInterface
    extends CRUDRepositoryInterface[CompanyAccessInheritanceMigration] {}
