package utils

import play.api.libs.json._
import repositories.PostgresProfile.api._

sealed case class Country(code: String, name: String, european: Boolean = false, transfer: Boolean = false)

object Country {

  val Afghanistan = Country("AFG", "Afghanistan")
  val AfriqueDuSud = Country("ZAF", "Afrique du Sud")
  val Albanie = Country("ALB", "Albanie")
  val Algerie = Country("DZA", "Algerie")
  val Allemagne = Country("DEU", "Allemagne",european = true)
  val Andorre = Country("AND", "Andorre", transfer = true)
  val Angola = Country("AGO", "Angola")
  val AntiguaEtBarbuda = Country("ATG", "Antigua-et-Barbuda")
  val ArabieSaoudite = Country("SAU", "Arabie saoudite")
  val Argentine = Country("ARG", "Argentine")
  val Armenie = Country("ARM", "Arménie")
  val Australie = Country("AUS", "Australie")
  val Autriche = Country("AUT", "Autriche",european = true)
  val Azerbaidjan = Country("AZE", "Azerbaïdjan")
  val Bahamas = Country("BHS", "Bahamas")
  val Bahrein = Country("BHR", "Bahreïn")
  val Bangladesh = Country("BGD", "Bangladesh")
  val Barbade = Country("BRB", "Barbade")
  val Belgique = Country("BEL", "Belgique",european = true)
  val Belize = Country("BLZ", "Bélize")
  val Benin = Country("BEN", "Bénin")
  val Bhoutan = Country("BTN", "Bhoutan")
  val Bielorussie = Country("BLR", "Biélorussie")
  val Birmanie = Country("MMR", "Birmanie")
  val Bolivie = Country("BOL", "Bolivie")
  val BosnieHerzegovine = Country("BIH", "Bosnie-Herzégovine")
  val Botswana = Country("BWA", "Botswana")
  val Bresil = Country("BRA", "Brésil")
  val Brunei = Country("BRN", "Brunei")
  val Bulgarie = Country("BGR", "Bulgarie",european = true)
  val Burkina = Country("BFA", "Burkina")
  val Burundi = Country("BDI", "Burundi")
  val Cambodge = Country("KHM", "Cambodge")
  val Cameroun = Country("CMR", "Cameroun")
  val Canada = Country("CAN", "Canada")
  val CapVert = Country("CPV", "Cap-Vert")
  val Centrafrique = Country("CAF", "Centrafrique")
  val Chili = Country("CHL", "Chili")
  val Chine = Country("CHN", "Chine")
  val Chypre = Country("CYP", "Chypre",european = true)
  val Colombie = Country("COL", "Colombie")
  val Comores = Country("COM", "Comores")
  val Congo = Country("COG", "Congo")
  val RepubliqueDemocratiqueDuCongo = Country("COD", "République démocratique du Congo")
  val IlesCook = Country("COK", "Îles Cook")
  val CoreeDuNord = Country("PRK", "Corée du Nord")
  val CoreeDuSud = Country("KOR", "Corée du Sud")
  val CostaRica = Country("CRI", "Costa Rica")
  val CoteDIvoire = Country("CIV", "Côte d'Ivoire")
  val Croatie = Country("HRV", "Croatie",european = true)
  val Cuba = Country("CUB", "Cuba")
  val Danemark = Country("DNK", "Danemark",european = true)
  val Djibouti = Country("DJI", "Djibouti")
  val RepubliqueDominicaine = Country("DOM", "République dominicaine")
  val Dominique = Country("DMA", "Dominique")
  val Egypte = Country("EGY", "Égypte")
  val EmiratsArabesUnis = Country("ARE", "Émirats arabes unis")
  val Equateur = Country("ECU", "Équateur")
  val Erythree = Country("ERI", "Érythrée")
  val Espagne = Country("ESP", "Espagne",european = true)
  val Estonie = Country("EST", "Estonie",european = true)
  val Eswatini = Country("SWZ", "Eswatini")
  val EtatsUnis = Country("USA", "États-Unis")
  val Ethiopie = Country("ETH", "Éthiopie")
  val Fidji = Country("FJI", "Fidji")
  val Finlande = Country("FIN", "Finlande",european = true)
  val France = Country("FRA", "France",european = true)
  val Gabon = Country("GAB", "Gabon")
  val Gambie = Country("GMB", "Gambie")
  val Georgie = Country("GEO", "Géorgie")
  val Ghana = Country("GHA", "Ghana")
  val Grece = Country("GRC", "Grèce",european = true)
  val Grenade = Country("GRD", "Grenade")
  val Guatemala = Country("GTM", "Guatémala")
  val Guinee = Country("GIN", "Guinée")
  val GuineeEquatoriale = Country("GNQ", "Guinée équatoriale")
  val GuineeBissao = Country("GNB", "Guinée-Bissao")
  val Guyana = Country("GUY", "Guyana")
  val Haiti = Country("HTI", "Haïti")
  val Honduras = Country("HND", "Honduras")
  val Hongrie = Country("HUN", "Hongrie",european = true)
  val Inde = Country("IND", "Inde")
  val Indonesie = Country("IDN", "Indonésie")
  val Irak = Country("IRQ", "Irak")
  val Iran = Country("IRN", "Iran")
  val Irlande = Country("IRL", "Irlande",european = true)
  val Islande = Country("ISL", "Islande",european = true)
  val Israel = Country("ISR", "Israël")
  val Italie = Country("ITA", "Italie",european = true)
  val Jamaique = Country("JAM", "Jamaïque")
  val Japon = Country("JPN", "Japon")
  val Jordanie = Country("JOR", "Jordanie")
  val Kazakhstan = Country("KAZ", "Kazakhstan")
  val Kenya = Country("KEN", "Kénya")
  val Kirghizstan = Country("KGZ", "Kirghizstan")
  val Kiribati = Country("KIR", "Kiribati")
  val Kosovo = Country("KOS", "Kosovo")
  val Koweit = Country("KWT", "Koweït")
  val Laos = Country("LAO", "Laos")
  val Lesotho = Country("LSO", "Lésotho")
  val Lettonie = Country("LVA", "Lettonie",european = true)
  val Liban = Country("LBN", "Liban")
  val Liberia = Country("LBR", "Libéria")
  val Libye = Country("LBY", "Libye")
  val Liechtenstein = Country("LIE", "Liechtenstein")
  val Lituanie = Country("LTU", "Lituanie",european = true)
  val Luxembourg = Country("LUX", "Luxembourg",european = true)
  val MacedoineDuNord = Country("MKD", "Macédoine du Nord")
  val Madagascar = Country("MDG", "Madagascar")
  val Malaisie = Country("MYS", "Malaisie")
  val Malawi = Country("MWI", "Malawi")
  val Maldives = Country("MDV", "Maldives")
  val Mali = Country("MLI", "Mali")
  val Malte = Country("MLT", "Malte",european = true)
  val Maroc = Country("MAR", "Maroc")
  val IlesMarshall = Country("MHL", "Îles Marshall")
  val Maurice = Country("MUS", "Maurice")
  val Mauritanie = Country("MRT", "Mauritanie")
  val Mexique = Country("MEX", "Mexique")
  val Micronesie = Country("FSM", "Micronésie")
  val Moldavie = Country("MDA", "Moldavie")
  val Monaco = Country("MCO", "Monaco")
  val Mongolie = Country("MNG", "Mongolie")
  val Montenegro = Country("MNE", "Monténégro")
  val Mozambique = Country("MOZ", "Mozambique")
  val Namibie = Country("NAM", "Namibie")
  val Nauru = Country("NRU", "Nauru")
  val Nepal = Country("NPL", "Népal")
  val Nicaragua = Country("NIC", "Nicaragua")
  val Niger = Country("NER", "Niger")
  val Nigeria = Country("NGA", "Nigéria")
  val Niue = Country("NIU", "Niue")
  val Norvege = Country("NOR", "Norvège",european = true)
  val NouvelleZelande = Country("NZL", "Nouvelle-Zélande")
  val Oman = Country("OMN", "Oman")
  val Ouganda = Country("UGA", "Ouganda")
  val Ouzbekistan = Country("UZB", "Ouzbékistan")
  val Pakistan = Country("PAK", "Pakistan")
  val Palaos = Country("PLW", "Palaos")
  val Panama = Country("PAN", "Panama")
  val PapouasieNouvelleGuinee = Country("PNG", "Papouasie-Nouvelle-Guinée")
  val Paraguay = Country("PRY", "Paraguay")
  val PaysBas = Country("NLD", "Pays-Bas",european = true)
  val Perou = Country("PER", "Pérou")
  val Philippines = Country("PHL", "Philippines")
  val Pologne = Country("POL", "Pologne",european = true)
  val Portugal = Country("PRT", "Portugal",european = true)
  val Qatar = Country("QAT", "Qatar")
  val Roumanie = Country("ROU", "Roumanie",european = true)
  val RoyaumeUni = Country("GBR", "Royaume-Uni")
  val Russie = Country("RUS", "Russie")
  val Rwanda = Country("RWA", "Rwanda")
  val SaintChristopheEtNieves = Country("KNA", "Saint-Christophe-et-Niévès")
  val SainteLucie = Country("LCA", "Sainte-Lucie")
  val SaintMarin = Country("SMR", "Saint-Marin")
  val SaintVincentEtLesGrenadines = Country("VCT", "Saint-Vincent-et-les-Grenadines")
  val Salomon = Country("SLB", "Salomon")
  val Salvador = Country("SLV", "Salvador")
  val Samoa = Country("WSM", "Samoa")
  val SaoTomeEtPrincipe = Country("STP", "Sao Tomé-et-Principe")
  val Senegal = Country("SEN", "Sénégal")
  val Serbie = Country("SRB", "Serbie")
  val Seychelles = Country("SYC", "Seychelles")
  val SierraLeone = Country("SLE", "Sierra Leone")
  val Singapour = Country("SGP", "Singapour")
  val Slovaquie = Country("SVK", "Slovaquie",european = true)
  val Slovenie = Country("SVN", "Slovénie",european = true)
  val Somalie = Country("SOM", "Somalie")
  val Soudan = Country("SDN", "Soudan")
  val SoudanDuSud = Country("SDS", "Soudan du Sud")
  val SriLanka = Country("LKA", "Sri Lanka")
  val Suede = Country("SWE", "Suède",european = true)
  val Suisse = Country("CHE", "Suisse", transfer = true)
  val Suriname = Country("SUR", "Suriname")
  val Syrie = Country("SYR", "Syrie")
  val Tadjikistan = Country("TJK", "Tadjikistan")
  val Tanzanie = Country("TZA", "Tanzanie")
  val Tchad = Country("TCD", "Tchad")
  val Tchequie = Country("CZE", "Tchéquie",european = true)
  val Thailande = Country("THA", "Thaïlande")
  val TimorOriental = Country("TLS", "Timor oriental")
  val Togo = Country("TGO", "Togo")
  val Tonga = Country("TON", "Tonga")
  val TriniteEtTobago = Country("TTO", "Trinité-et-Tobago")
  val Tunisie = Country("TUN", "Tunisie")
  val Turkmenistan = Country("TKM", "Turkménistan")
  val Turquie = Country("TUR", "Turquie")
  val Tuvalu = Country("TUV", "Tuvalu")
  val Ukraine = Country("UKR", "Ukraine")
  val Uruguay = Country("URY", "Uruguay")
  val Vanuatu = Country("VUT", "Vanuatu")
  val Vatican = Country("VAT", "Vatican")
  val Venezuela = Country("VEN", "Vénézuéla")
  val Vietnam = Country("VNM", "Vietnam")
  val Yemen = Country("YEM", "Yémen")
  val Zambie = Country("ZMB", "Zambie")
  val Zimbabwe = Country("ZWE", "Zimbabwé")

  val countries = List(Afghanistan, AfriqueDuSud, Albanie, Algerie, Allemagne, Andorre, Angola, AntiguaEtBarbuda, ArabieSaoudite, Argentine, Armenie,
    Australie, Autriche, Azerbaidjan, Bahamas, Bahrein, Bangladesh, Barbade, Belgique, Belize, Benin, Bhoutan, Bielorussie, Birmanie, Bolivie,
    BosnieHerzegovine, Botswana, Bresil, Brunei, Bulgarie, Burkina, Burundi, Cambodge, Cameroun, Canada, CapVert, Centrafrique, Chili, Chine,
    Chypre, Colombie, Comores, Congo, RepubliqueDemocratiqueDuCongo, IlesCook, CoreeDuNord, CoreeDuSud, CostaRica, CoteDIvoire, Croatie, Cuba,
    Danemark, Djibouti, RepubliqueDominicaine, Dominique, Egypte, EmiratsArabesUnis, Equateur, Erythree, Espagne, Estonie, Eswatini, EtatsUnis,
    Ethiopie, Fidji, Finlande, France, Gabon, Gambie, Georgie, Ghana, Grece, Grenade, Guatemala, Guinee, GuineeEquatoriale, GuineeBissao, Guyana,
    Haiti, Honduras, Hongrie, Inde, Indonesie, Irak, Iran, Irlande, Islande, Israel, Italie, Jamaique, Japon, Jordanie, Kazakhstan, Kenya, Kirghizstan,
    Kiribati, Kosovo, Koweit, Laos, Lesotho, Lettonie, Liban, Liberia, Libye, Liechtenstein, Lituanie, Luxembourg, MacedoineDuNord, Madagascar, Malaisie,
    Malawi, Maldives, Mali, Malte, Maroc, IlesMarshall, Maurice, Mauritanie, Mexique, Micronesie, Moldavie, Monaco, Mongolie, Montenegro, Mozambique,
    Namibie, Nauru, Nepal, Nicaragua, Niger, Nigeria, Niue, Norvege, NouvelleZelande, Oman, Ouganda, Ouzbekistan, Pakistan, Palaos, Panama,
    PapouasieNouvelleGuinee, Paraguay, PaysBas, Perou, Philippines, Pologne, Portugal, Qatar, Roumanie, RoyaumeUni, Russie, Rwanda, SaintChristopheEtNieves,
    SainteLucie, SaintMarin, SaintVincentEtLesGrenadines, Salomon, Salvador, Samoa, SaoTomeEtPrincipe, Senegal, Serbie, Seychelles, SierraLeone, Singapour,
    Slovaquie, Slovenie, Somalie, Soudan, SoudanDuSud, SriLanka, Suede, Suisse, Suriname, Syrie, Tadjikistan, Tanzanie, Tchad, Tchequie, Thailande,
    TimorOriental, Togo, Tonga, TriniteEtTobago, Tunisie, Turkmenistan, Turquie, Tuvalu, Ukraine, Uruguay, Vanuatu, Vatican, Venezuela, Vietnam, Yemen,
    Zambie, Zimbabwe)


  def fromCode(code: String) = {
    countries.find(_.code == code).head
  }

  def fromName(name: String) = {
    countries.find(_.name == name).head
  }

  implicit val reads = new Reads[Country] {
    def reads(json: JsValue): JsResult[Country] = json.validate[String].map(fromName(_))
  }
  implicit val writes = Json.writes[Country]

  implicit val CountryColumnType = MappedColumnType.base[Country, String](_.name, Country.fromName(_))

  implicit val countryListColumnType = MappedColumnType.base[List[Country], List[String]](
    _.map(_.name),
    _.map(Country.fromName)
  )
}