# --- !Ups

CREATE TABLE company_data (
    siren VARCHAR,
    nic VARCHAR,
    siret VARCHAR,
    statutDiffusionEtablissement VARCHAR,
    dateCreationEtablissement VARCHAR,
    trancheEffectifsEtablissement VARCHAR,
    anneeEffectifsEtablissement VARCHAR,
    activitePrincipaleRegistreMetiersEtablissement VARCHAR,
    dateDernierTraitementEtablissement VARCHAR,
    etablissementSiege VARCHAR,
    etatAdministratifUniteLegale VARCHAR,
    statutDiffusionUniteLegale VARCHAR,
    unitePurgeeUniteLegale VARCHAR,
    dateCreationUniteLegale VARCHAR,
    categorieJuridiqueUniteLegale VARCHAR,
    denominationUniteLegale VARCHAR,
    sigleUniteLegale VARCHAR,
    denominationUsuelle1UniteLegale VARCHAR,
    denominationUsuelle2UniteLegale VARCHAR,
    denominationUsuelle3UniteLegale VARCHAR,
    sexeUniteLegale VARCHAR,
    nomUniteLegale VARCHAR,
    nomUsageUniteLegale VARCHAR,
    prenom1UniteLegale VARCHAR,
    prenom2UniteLegale VARCHAR,
    prenom3UniteLegale VARCHAR,
    prenom4UniteLegale VARCHAR,
    prenomUsuelUniteLegale VARCHAR,
    pseudonymeUniteLegale VARCHAR,
    activitePrincipaleUniteLegale VARCHAR,
    nomenclatureActivitePrincipaleUniteLegale VARCHAR,
    identifiantAssociationUniteLegale VARCHAR,
    economieSocialeSolidaireUniteLegale VARCHAR,
    caractereEmployeurUniteLegale VARCHAR,
    trancheEffectifsUniteLegale VARCHAR,
    anneeEffectifsUniteLegale VARCHAR,
    nicSiegeUniteLegale VARCHAR,
    dateDernierTraitementUniteLegale VARCHAR,
    categorieEntreprise VARCHAR,
    anneeCategorieEntreprise VARCHAR,
    complementAdresseEtablissement VARCHAR,
    numeroVoieEtablissement VARCHAR,
    indiceRepetitionEtablissement VARCHAR,
    typeVoieEtablissement VARCHAR,
    libelleVoieEtablissement VARCHAR,
    codePostalEtablissement VARCHAR,
    libelleCommuneEtablissement VARCHAR,
    libelleCommuneEtrangerEtablissement VARCHAR,
    distributionSpecialeEtablissement VARCHAR,
    codeCommuneEtablissement VARCHAR,
    codeCedexEtablissement VARCHAR,
    libelleCedexEtablissement VARCHAR,
    codePaysEtrangerEtablissement VARCHAR,
    libellePaysEtrangerEtablissement VARCHAR,
    complementAdresse2Etablissement VARCHAR,
    numeroVoie2Etablissement VARCHAR,
    indiceRepetition2Etablissement VARCHAR,
    typeVoie2Etablissement VARCHAR,
    libelleVoie2Etablissement VARCHAR,
    codePostal2Etablissement VARCHAR,
    libelleCommune2Etablissement VARCHAR,
    libelleCommuneEtranger2Etablissement VARCHAR,
    distributionSpeciale2Etablissement VARCHAR,
    codeCommune2Etablissement VARCHAR,
    codeCedex2Etablissement VARCHAR,
    libelleCedex2Etablissement VARCHAR,
    codePaysEtranger2Etablissement VARCHAR,
    libellePaysEtranger2Etablissement VARCHAR,
    etatAdministratifEtablissement VARCHAR,
    enseigne1Etablissement VARCHAR,
    enseigne2Etablissement VARCHAR,
    enseigne3Etablissement VARCHAR,
    denominationUsuelleEtablissement VARCHAR,
    activitePrincipaleEtablissement VARCHAR,
    nomenclatureActivitePrincipaleEtablissement VARCHAR,
    caractereEmployeurEtablissement VARCHAR
);

# --- !Downs

DROP TABLE company_data;