package repositories.reportmetadata

import models.report.reportmetadata.ReportMetadata
import repositories.CRUDRepositoryInterface

trait ReportMetadataRepositoryInterface extends CRUDRepositoryInterface[ReportMetadata] {}
