name: Build, format & test workflow

on: [push]
env:
  TEST_PGHOST: localhost
  POSTGRES_USER: signalconso
  POSTGRES_DB: test_signalconso

jobs:
  # This workflow contains a single job called "greet"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    # Steps represent a sequence of tasks that will be
    # executed as part of the job
    steps:
      - uses: actions/checkout@v3
      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17
          cache: 'sbt'

      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client
      - run: whoami
      - run: psql -d postgresql://${{POSTGRES_USER}}@${{TEST_PGHOST}}/${{POSTGRES_DB}} -p 5432 -c "CREATE EXTENSION pg_trgm;"
      - name: Build and Test
        run: sbt scalafmtCheck scalafmtSbtCheck -v +test

