name: Build, format & test workflow

on: [push]
env:
  USER: signalconso
  USE_TEXT_LOGS: true

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: signalconso
          POSTGRES_DB: test_signalconso
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4
      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17
          cache: sbt
      - uses: sbt/setup-sbt@v1
        with:
          sbt-runner-version: 1.9.9

      - run: sudo apt-get update
      - run: sudo apt-get install postgresql-client
      - run: whoami
      - run: psql -d postgresql://signalconso@localhost/test_signalconso -p 5432 -c "CREATE EXTENSION pg_trgm;"
      - name: Build and Test
        run: sbt scalafmtCheckAll scalafmtSbtCheck -v +test